# Generated by Django 2.0.6 on 2018-10-07 10:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180901_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='voucheritemmapping',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='voucheritemmapping',
            name='voucher_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Voucher', unique=True),
        ),
    ]
